=== hamoungh/safar/output/Opera.dtd
<!ELEMENT 	Service EMPTY>
<!ATTLIST 	Service name ID #REQUIRED>
<!ATTLIST 	Service canMigrate (true|false) 'false'>
<!ATTLIST 	Service runsInContainer IDREF #REQUIRED>

<!ELEMENT	 Demand EMPTY>
<!ATTLIST    Demand CPUDemand CDATA #REQUIRED>
<!ATTLIST    Demand DiskDemand CDATA #REQUIRED>
<!ATTLIST    Demand OtherDemand CDATA #IMPLIED> 

<!ELEMENT    Call (Demand)>
<!ATTLIST    Call type (s|a|f) 's'>
<!ATTLIST    Call caller IDREF #REQUIRED>
<!ATTLIST    Call callee IDREF #REQUIRED>
<!ATTLIST    Call invocations CDATA #REQUIRED>
<!ATTLIST    Call bytesSent CDATA #IMPLIED>
<!ATTLIST    Call bytesReceived CDATA #IMPLIED>

<!ELEMENT 	Scenario (Call+)>
<!ATTLIST 	Scenario name CDATA #REQUIRED>
<!ATTLIST 	Scenario triggeredByService IDREF #REQUIRED>


<!ELEMENT 	Scenarios (ServiceDescription?,Services,ScenarioDescription?,Scenario+)>
<!ELEMENT 	ServiceDescription (#PCDATA)> 
<!ELEMENT 	ScenarioDescription (#PCDATA)>
<!ELEMENT 	Services (Service+)>


<!ELEMENT   Node EMPTY>
<!ATTLIST   Node  name ID #REQUIRED>
<!ATTLIST   Node  CPURatio CDATA #REQUIRED>
<!ATTLIST   Node  DiskRatio CDATA #REQUIRED>
<!ATTLIST   Node  DiskParallelism CDATA '1'>
<!ATTLIST   Node  CPUParallelism CDATA '1'>
<!ATTLIST   Node  type (server|client|delay) 'server'>

<!ELEMENT   Container EMPTY>
<!ATTLIST   Container  name ID #REQUIRED> 
<!ATTLIST   Container  runsOnNode IDREF #REQUIRED>
<!ATTLIST   Container  server (true|false) 'true'>
<!ATTLIST   Container  parallelism CDATA '1000'>  
<!ATTLIST 	Container  canMigrate (true|false) 'false'>
<!ELEMENT 	Middlware  EMPTY>
<!ATTLIST   Middlware  name ID #REQUIRED>
<!ATTLIST   Middlware  fixedOverheadSend CDATA '20'>
<!ATTLIST   Middlware  fixedOverheadReceive CDATA '20'>
<!ATTLIST   Middlware  overheadPerByteSent CDATA '2'>
<!ATTLIST   Middlware  overheadPerByteReceived CDATA '2'>

<!ELEMENT 	Network EMPTY>
<!ATTLIST   Network  name ID #REQUIRED>
<!ATTLIST   Network  latency CDATA '100'>
<!ATTLIST   Network  overheadPerByte CDATA '0.002'>
<!ATTLIST   Network  connectsNodes IDREFS #REQUIRED>

<!ELEMENT   Cluster (ContainerDescription?, Container+)>
<!ATTLIST   Cluster name ID #REQUIRED> 

<!ELEMENT Topology (NodeDescription?, Node+, Cluster+,  MiddlwareDescription?, Middlware+, NetworkDescription?, Network+)>
<!ELEMENT NodeDescription (#PCDATA)>
<!ELEMENT ContainerDescription (#PCDATA)>
<!ELEMENT MiddlwareDescription (#PCDATA)>
<!ELEMENT NetworkDescription (#PCDATA)>
   
   
<!ELEMENT ThinkTimes  (ThinkTime+)>
<!ELEMENT ThinkTime  EMPTY>
<!ATTLIST ThinkTime scenario CDATA #REQUIRED>
<!ATTLIST ThinkTime time CDATA #REQUIRED>

<!ELEMENT ResponseTime EMPTY>
<!ATTLIST ResponseTime scenario CDATA  #REQUIRED>
<!ATTLIST ResponseTime minResponseTime CDATA   '0'>
<!ATTLIST ResponseTime maxResponseTime CDATA  #REQUIRED>

<!ELEMENT Requirements  (ResponseTime+)>
<!ELEMENT WorkloadMixes (Mix*)>
<!ATTLIST WorkloadMixes openModel (true|false) 'false'>
<!ELEMENT Mix EMPTY>
<!ATTLIST Mix scenario CDATA #REQUIRED>
<!ATTLIST Mix load CDATA #REQUIRED>
<!ELEMENT Users (#PCDATA)>

<!ELEMENT Workloads (Users, WorkloadMixes+, ThinkTimes)>
<!ATTLIST Workloads kind (HL|ML|VHL) 'ML'>

<!ELEMENT Model (Scenarios, Topology, Workloads, Requirements)>

=== hamoungh/safar/output/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Model SYSTEM "Opera.dtd">
<Model>
    <Scenarios>
        <Services>
            <Service canMigrate="false" name="BrowserClient" runsInContainer="ClientContainer"/>
            <Service canMigrate="false" name="BrowserLB" runsInContainer="LBContainer"/>
            <Service canMigrate="false" name="BrowseService1" runsInContainer="Container1"/>
            <Service canMigrate="false" name="BrowseService2" runsInContainer="Container2"/>
            <Service canMigrate="false" name="BrowseService3" runsInContainer="Container3"/>
            <Service canMigrate="false" name="BrowseService4" runsInContainer="Container4"/>
            <Service canMigrate="false" name="BrowseService5" runsInContainer="Container5"/>
            <Service canMigrate="false" name="BrowseService6" runsInContainer="Container6"/>
        </Services>
        <Scenario name="select" triggeredByService="BrowserClient">
            <Call bytesReceived="0" bytesSent="0" callee="BrowserLB"
                caller="BrowserClient" invocations="1" type="s">
                <Demand CPUDemand="0" DiskDemand="0"/>
            </Call>
            <Call bytesReceived="0" bytesSent="0"
                callee="BrowseService1" caller="BrowserLB"
                invocations="1" type="s">
                <Demand CPUDemand="0.015" DiskDemand="0"/>
            </Call>
            <Call bytesReceived="0" bytesSent="0"
                callee="BrowseService2" caller="BrowserLB"
                invocations="1" type="s">
                <Demand CPUDemand="0.015" DiskDemand="0"/>
            </Call>
            <Call bytesReceived="0" bytesSent="0"
                callee="BrowseService3" caller="BrowserLB"
                invocations="1" type="s">
                <Demand CPUDemand="0.015" DiskDemand="0"/>
            </Call>
            <Call bytesReceived="0" bytesSent="0"
                callee="BrowseService4" caller="BrowserLB"
                invocations="1" type="s">
                <Demand CPUDemand="0.015" DiskDemand="0"/>
            </Call>
            <Call bytesReceived="0" bytesSent="0"
                callee="BrowseService5" caller="BrowserLB"
                invocations="1" type="s">
                <Demand CPUDemand="0.015" DiskDemand="0"/>
            </Call>
            <Call bytesReceived="0" bytesSent="0"
                callee="BrowseService6" caller="BrowserLB"
                invocations="1" type="s">
                <Demand CPUDemand="0.015" DiskDemand="0"/>
            </Call>
        </Scenario>
    </Scenarios>
    <Topology>
        <Node CPUParallelism="1" CPURatio="1" DiskParallelism="1"
            DiskRatio="1" name="ClientHost" type="client"/>
        <Node CPUParallelism="1" CPURatio="1" DiskParallelism="1"
            DiskRatio="1" name="LBHost" type="server"/>
        <Node CPUParallelism="1" CPURatio="1" DiskParallelism="1"
            DiskRatio="1" name="Host1" type="server"/>
        <Node CPUParallelism="1" CPURatio="1" DiskParallelism="1"
            DiskRatio="1" name="Host2" type="server"/>
        <Node CPUParallelism="1" CPURatio="1" DiskParallelism="1"
            DiskRatio="1" name="Host3" type="server"/>
        <Node CPUParallelism="1" CPURatio="1" DiskParallelism="1"
            DiskRatio="1" name="Host4" type="server"/>
        <Node CPUParallelism="1" CPURatio="1" DiskParallelism="1"
            DiskRatio="1" name="Host5" type="server"/>
        <Node CPUParallelism="1" CPURatio="1" DiskParallelism="1"
            DiskRatio="1" name="Host6" type="server"/>
        <Cluster name="ClientCluster">
            <Container canMigrate="false" name="ClientContainer"
                parallelism="1000" runsOnNode="ClientHost" server="false"/>
        </Cluster>
        <Cluster name="WebCluster">
            <Container canMigrate="false" name="LBContainer"
                parallelism="1000" runsOnNode="LBHost" server="true"/>
            <Container canMigrate="false" name="Container1"
                parallelism="400" runsOnNode="Host1" server="true"/>
            <Container canMigrate="false" name="Container2"
                parallelism="400" runsOnNode="Host2" server="true"/>
            <Container canMigrate="false" name="Container3"
                parallelism="400" runsOnNode="Host3" server="true"/>
            <Container canMigrate="false" name="Container4"
                parallelism="400" runsOnNode="Host4" server="true"/>
            <Container canMigrate="false" name="Container5"
                parallelism="400" runsOnNode="Host5" server="true"/>
            <Container canMigrate="false" name="Container6"
                parallelism="400" runsOnNode="Host6" server="true"/>
        </Cluster>
        <Middlware fixedOverheadReceive="0" fixedOverheadSend="0"
            name="http" overheadPerByteReceived="0" overheadPerByteSent="0"/>
        <Network
            connectsNodes="ClientHost LBHost Host1 Host2 Host3 Host4 Host5 Host6"
            latency="0" name="Internet" overheadPerByte="0"/>
    </Topology>
    <Workloads kind="HL">
        <Users>850</Users>
        <WorkloadMixes openModel="false">
            <Mix load="850" scenario="select"/>
        </WorkloadMixes>
        <ThinkTimes>
            <ThinkTime scenario="select" time="0.1"/>
        </ThinkTimes>
    </Workloads>
    <Requirements>
        <ResponseTime maxResponseTime="100000" minResponseTime="100" scenario="select"/>
    </Requirements>
</Model>
